### ISSUE TITLE
ali__get_full_cmd does not work on mac

### ISSUE THREAD

**Issue by awreece** [asciimoo/ali#1]
The example in the gif didn't work for me (zsh 5.0.8 (x86_64-apple-darwin15.0)):

```
/tmp% ali register ls ls -G
/tmp% ali list
function ls() {  ls -G "$@"; }
/tmp% ls
ls: maximum nested function level reached
```

Some output that might be helpful:

```
/tmp% ali__get_full_cmd ps
/tmp% whereis ps
/bin/ps
/tmp% whereis ps |  grep -v "\.\$"
/bin/ps
/tmp% whereis ps |  grep -v "\.\$"  | cut -s -d ' ' -f 2 
```

It looks like the Mac `whereis` (derived from BSD) has different output semantics than the Linux one. Why `whereis` instead of `which`, etc? For that matter, won't the use of `whereis` mean it is impossible to alias a function (e.g. `function hi() { echo hi }; ali define hi hi mom`)?

**Comment by asciimoo** [comment]
@awreece thanks the report, I've tested it only on linux (debian). The problem with `where` is exactly what you mention, it returns with the function if a function has the same name as an executable, which causes infinite recursion.

**Comment by asciimoo** [comment]
@awreece could you verify that 089ad4f solves the issue?

**Comment by awreece** [comment]
Fixed.
