### ISSUE TITLE
A few issues with this

### ISSUE THREAD

**Issue by Earnestly** [asciimoo/ali#2]
- Uses `#!/bin/sh` and `ali.sh` when this script is in fact bash.
- Hardcodes `HOME/.config` instead of conforming to XDG Basedir such as `${XDG_CONFIG_HOME:-$HOME/.config}/ali`.
- Uses `echo` with flags.
- Shells have the ability to use functions obviated the need for this script entirely.

**Comment by asciimoo** [comment]
@Earnestly thanks, agree with your observations. Could you contribute the fixes?

**Comment by awreece** [comment]
> Shells have the ability to use functions obviated the need for this script entirely.

Somewhat true, however I think `ali` makes life sufficiently easier to justify its existence:
- Functions capture the arguments whereas aliases forwards them. Compare:
  
  ```
   function hi () { echo hi }
  ```
  
  to 
  
  ```
  alias hi=echo hi
  ```
  
  when you execute `hi mom`. `ali` tries to preserve the alias semantics.
- `ali` provides a easy way to register and unregister functions; the equivalent of 
  
  ```
  ali register hi echo hi
  ```
  
  is 
  
  ```
  echo 'function hi () { echo hi "$@" }' >~/.zsh_autoload_functions/hi
  ```
  
  This is substantially more verbose and requires knowledge of specific implementation details (e.g. where autoloaded functions are located for your shell). For shells without autoloaded functions, `ali delete hi` is _way_ easier and "safer" than `sed -i '/^function () hi/d' ~/.bashrc`

**Comment by Earnestly** [comment]
@awreece.  First you don't need to type `function` (it isn't even POSIX) which makes it shorter than your alias, second your example doesn't even need to be a function, third if you're using bash you need to terminate the final command with a `;`.

_edit: To demonstrate as you added a needless space between `hi` and the opening parenthesis: `hi(){echo hi;}`_

Making a functions script is not difficult, shells have builtin mechanisms for undefining aliases and functions via `unset` and as for deleting functions straight out of the file with sed, it does assume all functions are one-liners and both bash and zsh offer the ability to do multi-line edits.  So no, it's not as "safe" or robust as simply removing an unused function.

Similarly a simpler approach would be to just keep each function in a file and load them which allows you to remove them with just `rm` and `unset -f`.

Also your zsh example is incorrect as `HOME/.zsh_autoload_functions` is not part of `fpath` by default and would not be looked at.

Sorry but what exactly is the point of this?  Is the goal to somehow make writing functions more vague, more dangerous with the addition of `eval` usage and less transparent because, uh, why?

@asciimoo Is repo deletion a valid contribution?

**Comment by asciimoo** [comment]
@Earnestly thanks the constructive comments, i'll fix the technical issues
